name: Upload Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Environment Variables File for Production
        run: |
          echo "NEXT_PUBLIC_S3_UPLOAD_KEY=$NEXT_PUBLIC_S3_UPLOAD_KEY" >> .env.local
          echo "NEXT_PUBLIC_S3_UPLOAD_SECRET=$NEXT_PUBLIC_S3_UPLOAD_SECRET" >> .env.local
          echo "NEXT_PUBLIC_S3_UPLOAD_BUCKET=$NEXT_PUBLIC_S3_UPLOAD_BUCKET" >> .env.local
          echo "NEXT_PUBLIC_S3_UPLOAD_REGION=$NEXT_PUBLIC_S3_UPLOAD_REGION" >> .env.local
        env:
          NEXT_PUBLIC_S3_UPLOAD_KEY: ${{ secrets.NEXT_PUBLIC_S3_UPLOAD_KEY }}
          NEXT_PUBLIC_S3_UPLOAD_SECRET: ${{ secrets.NEXT_PUBLIC_S3_UPLOAD_SECRET }}
          NEXT_PUBLIC_S3_UPLOAD_BUCKET: ${{ secrets.NEXT_PUBLIC_S3_UPLOAD_BUCKET }}
          NEXT_PUBLIC_S3_UPLOAD_REGION: 'ap-northeast-2'

      - run: npm install
      - run: npm run build

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_MANAGER_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-2' # optional: defaults to us-east-1
          SOURCE_DIR: 'out' # optional: defaults to entire repository
