name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - run: npm install
      - run: npm run build
        env:
          NEXT_PUBLIC_CLIENT_ID: ${{ secrets.SOCIAL_LOGIN_CLIENT_ID }}
          NEXT_PUBLIC_PATHNAME: ${{ secrets.SOCIAL_LOGIN_PATHNAME }}
          NEXT_PUBLIC_REDIRECT_URI: ${{ secrets.SOCIAL_LOGIN_REDIRECT_URI }}
          NEXT_PUBLIC_RESPONSE_TYPE: ${{ secrets.SOCIAL_LOGIN_RESPONSE_TYPE }}
          NEXT_PUBLIC_FRONT_URI: ${{ secrets.FRONT_URI }}

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # AWS_REGION: 'ap-northeast-2' # optional: defaults to us-east-1
          SOURCE_DIR: 'out' # optional: defaults to entire repository

      - name: CloudFront Invalidate Cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'
